# Generated by Django 2.0 on 2018-09-04 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name_plural': 'Social Media Links'},
        ),
        migrations.AddField(
            model_name='social',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 4, 13, 22, 11, 827388, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
