# Generated by Django 2.1.1 on 2018-09-04 14:18

from django.db import migrations, models
import django.db.models.deletion
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20180904_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image.models.get_image_path)),
            ],
        ),
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='upload',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='image.Thing'),
        ),
    ]
